### ISSUE TITLE
Gem fails to install

### ISSUE THREAD

**Issue by christophersaxey** [gmodarelli/ruby-deepclone#7]
First off, thanks for sharing your code. I'm new to ruby, so if this is something simple please forgive my ignorance. I tried installing your gem today and was met with this error:
gem install -n . ruby_deep_clone
Building native extensions.  This could take a while...
ERROR:  Error installing ruby_deep_clone:
    ERROR: Failed to build gem native extension.

/usr/bin/ruby1.8 extconf.rb
creating Makefile

make
gcc -I. -I/usr/lib/ruby/1.8/x86_64-linux -I/usr/lib/ruby/1.8/x86_64-linux -I.   -fPIC -fno-strict-aliasing -g -g -O2  -fPIC   -c deep_clone.c
In file included from deep_clone.c:1:
deep_clone.h:5:21: error: ruby/st.h: No such file or directory
deep_clone.h:6:26: error: ruby/version.h: No such file or directory
In file included from deep_clone.c:1:
deep_clone.h:61: error: expected ‘)’ before ‘key’
deep_clone.c:34: error: expected ‘)’ before ‘key’
deep_clone.c: In function ‘hash_each’:
deep_clone.c:47: error: ‘ST_CONTINUE’ undeclared (first use in this function)
deep_clone.c:47: error: (Each undeclared identifier is reported only once
deep_clone.c:47: error: for each function it appears in.)
deep_clone.c: In function ‘clone_object’:
deep_clone.c:80: error: ‘st_data_t’ undeclared (first use in this function)
deep_clone.c:116: error: ‘st_table’ undeclared (first use in this function)
deep_clone.c:116: error: ‘tbl’ undeclared (first use in this function)
deep_clone.c:116: error: ‘ROBJECT_EMBED’ undeclared (first use in this function)
deep_clone.c:116: error: ‘struct RClass’ has no member named ‘iv_index_tbl’
deep_clone.c:116: error: ‘struct RObject’ has no member named ‘as’
deep_clone.c:120: error: ‘clone_variable’ undeclared (first use in this function)
make: **\* [deep_clone.o] Error 1

I'm running ruby 1.8.7 (I know, upgrade but work just hasn't given me time yet) on Debian squeeze 6.0.8 x64
Thanks for your time.

**Comment by balmma** [comment]
```
Hi
We've just dropped support for pre 1.9.3 Versions due to
compatibility issues.
An older version (e.g. 0.3.0) should still work with Ruby 1.8.
Cheers
MatOn 02/08/2014 06:59 AM,
  christophersaxey wrote:

  First off, thanks for sharing your code. I'm new to ruby, so if
    this is something simple please forgive my ignorance. I tried
    installing your gem today and was met with this error:
    gem install -n . ruby_deep_clone
    Building native extensions. This could take a while...
    ERROR: Error installing ruby_deep_clone:
    ERROR: Failed to build gem native extension.
  /usr/bin/ruby1.8 extconf.rb
    creating Makefile
  make
    gcc -I. -I/usr/lib/ruby/1.8/x86_64-linux
    -I/usr/lib/ruby/1.8/x86_64-linux -I. -fPIC -fno-strict-aliasing
    -g -g -O2 -fPIC -c deep_clone.c
    In file included from deep_clone.c:1:
    deep_clone.h:5:21: error: ruby/st.h: No such file or directory
    deep_clone.h:6:26: error: ruby/version.h: No such file or
    directory
    In file included from deep_clone.c:1:
    deep_clone.h:61: error: expected ‘)’ before ‘key’
    deep_clone.c:34: error: expected ‘)’ before ‘key’
    deep_clone.c: In function ‘hash_each’:
    deep_clone.c:47: error: ‘ST_CONTINUE’ undeclared (first use in
    this function)
    deep_clone.c:47: error: (Each undeclared identifier is reported
    only once
    deep_clone.c:47: error: for each function it appears in.)
    deep_clone.c: In function ‘clone_object’:
    deep_clone.c:80: error: ‘st_data_t’ undeclared (first use in
    this function)
    deep_clone.c:116: error: ‘st_table’ undeclared (first use in
    this function)
    deep_clone.c:116: error: ‘tbl’ undeclared (first use in this
    function)
    deep_clone.c:116: error: ‘ROBJECT_EMBED’ undeclared (first use
    in this function)
    deep_clone.c:116: error: ‘struct RClass’ has no member named
    ‘iv_index_tbl’
    deep_clone.c:116: error: ‘struct RObject’ has no member named
    ‘as’
    deep_clone.c:120: error: ‘clone_variable’ undeclared (first use
    in this function)
    make: *** [deep_clone.o] Error 1
  I'm running ruby 1.8.7 (I know, upgrade but work just hasn't
    given me time yet) on Debian squeeze 6.0.8 x64
    Thanks for your time.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by christophersaxey** [comment]
Thanks! Maybe now I can convince them it's time to upgrade.
